[training]
batch_size = 32
epochs = 1000
learning_rate = 0.05
test_split = 0.2

[data]
csv_path = data/synthetic_data.csv
input_dim = 4
output_dim = 1
skip_index_0 = false

# Define hidden layers in order: size and activation function
# Available activations: relu, leaky_relu, sigmoid, tanh, identity
[layers]
hidden_1_size = 16
hidden_1_activation = leaky_relu
hidden_2_size = 10
hidden_2_activation = leaky_relu
output_activation = identity
